version: '3'
services:

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  
    depends_on:
      - auth
      - notifications
      - realtime
    networks:
      - internal
    restart: on-failure


  rabbitmq:
    image: "rabbitmq:3-management"

    networks:
      - internal
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: on-failure


  mongodb:
    image: mongo:latest
    networks:
      - internal
    restart: on-failure




  auth:
    build: ./authService
    env_file:
      - ./authService/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - internal
    restart: on-failure

  notifications:
    build: ./notificationService
    env_file:
      - ./notificationService/.env
    networks:
      - internal
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure


  realtime:
    build: ./realTimeService
    env_file:
      - ./realTimeService/.env
    networks:
      - internal
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure


networks:
  internal:
    driver: bridge
